app/routes.php
<?php

// Nos mostrará el formulario de login.
Route::get('login', 'AuthController@showLogin');

// Validamos los datos de inicio de sesión.
Route::post('login', 'AuthController@postLogin');
Route::get('/panel/logout', 'AuthController@logOut');
Route::get('prueba', function(){
	return Hash::make('admin');
});
Route::get('/', function()
{
	return View::make('home', array(
		'activo'=>'inicio'
	));
});

Route::post('documentacion_pais', function()
{
	$pais = Input::get('pais');

	if (!View::exists('visas/'.$pais))
	{
	    App::abort(404);
	}

	return View::make('documentacion_pais', array(
		'pais'=>$pais,
		'nombre_pais'=>Visa::getNombrePais($pais)
	));
});

Route::get('empresa', function()
{
	$secciones_empresa = SeccionEmpresa::orderBy('id')->get();
	return View::make('empresa', array(
		'secciones_empresa'=>$secciones_empresa,
		'activo'=>'empresa'
	));
});
Route::get('/planes/nacionales', function()
{
	$planes = Plan::with('plan_tipo')->where('plan_tipo_id', 1)->paginate(6);
	return View::make('planes_nacionales', array(
		'planes'=> $planes,
		'activo'=>'planes'
	));
});
Route::get('/planes/internacionales', function()
{
	$planes = Plan::with('plan_tipo')->where('plan_tipo_id', 2)->paginate(6);
	return View::make('planes_internacionales', array(
		'planes'=> $planes,
		'activo'=>'planes'
	));
});
Route::get('/cruceros', function()
{
	$cruceros = Crucero::paginate(4);
	return View::make('cruceros', array(
		'cruceros'=> $cruceros,
		'activo'=>'cruceros'
	));
});
Route::get('/promociones', function()
{
	$promociones = Promocion::paginate(4);
	return View::make('promociones', array(
		'promociones'=> $promociones,
		'activo'=>'promociones'
	));
});
Route::resource('/seguro', 'SolicitudSeguroController');
Route::resource('/contacto', 'ContactoController');

Route::get('seguro_success', function(){
	return View::make('seguro_registrado', array(
		'activo'=>'seguro'
	));
});
Route::get('documentacion', function()
{
	return View::make('documentacion', array(
		'activo'=>'documentacion',
		'array_paises'=>Visa::paisesArray()
	));
});
Route::get('conoce_mas', function()
{
    return View::make('conoce_mas', array(
        'activo'=>'conoce_mas'
    ));
});

Route::get('no_auth', function()
{
	return View::make('admin/no_auth');
});

Route::group(array('before' => 'auth'), function()
{
	Route::get('/panel/cambiar_contrasena', 'AuthController@changePassword');
    Route::post('/panel/cambiar_contrasena', 'AuthController@updatePassword');

    Route::resource('/panel/creditos', 'CreditoController');
    Route::get('panel/search_by_doc', 'CreditoController@searchByDoc');
    Route::post('panel/search_by_doc_result', 'CreditoController@searchByDocResult');
    Route::get('panel/nuevo_pago/{id_credito}', function($id_credito)
    {
        $abono = new Abono();
        return View::make('creditos/nuevo_pago', array(
            'activo'=>'empresa',
            'id_credito'=>$id_credito,
            'abono'=>$abono
        ));
    });

    Route::resource('/panel/abonos', 'AbonoController');
});
Route::group(array('before' => 'auth|roles:1,no_auth'), function()
{
    Route::get('panel/nomina', 'CreditoController@searchNomina');
    Route::get('panel/closers_by_office', 'CreditoController@closersByOffice');
    Route::post('panel/search_nomina_result', 'CreditoController@searchNominaResult');

    Route::resource('panel/usuarios', 'UserController');
    Route::resource('/panel/planes', 'PlanController');
    Route::resource('/panel/oficinas', 'OficinaController');
    Route::resource('/panel/closers', 'CloserController');
    Route::resource('/panel/cruceros', 'CruceroController');
    Route::resource('/panel/promociones', 'PromocionController');
    Route::resource('/panel/documentacion', 'DocumentacionController');
    Route::resource('/panel', 'PaginaPrincipalController');

});

Route::group(array('before' => 'auth|roles:2-3,no_auth'), function()
{
	Route::get('ventas', function()
    {
        return View::make('admin/ventas', array(
            'activo'=>'empresa',
        ));
    });
});

app/views/promociones/form.blade.php
@extends('admin.layout')
<?php
    if ($promocion->exists):
        $form_data = array('route' => array('panel.promociones.update', $promocion->id), 'method' => 'PATCH', 'files' => true);
    else:
        $form_data = array('route' => 'panel.promociones.store', 'method' => 'POST', 'files' => true);
    endif;

?>
@section('content')
<div class="row">
  <div class="col-lg-12">
    <h1>Promocion <small>{{ $action }}</small></h1>
    <ol class="breadcrumb">
      <li><a href="{{url('panel/promociones')}}"><i class="icon-dashboard"></i> Promociones</a></li>
      <li class="active"><i class="icon-file-alt"></i> {{ $action }}</li>
    </ol>
  </div>
</div><!-- /.row -->
<div>
	@include ('errors', array('errors' => $errors)) 
</div>
<div>
	{{ Form::model($promocion,$form_data, array('role' => 'form')) }}
	    <div class="form-group">
	      	{{ Form::label('title', 'Título') }}
	     	{{ Form::text('title', null, array('placeholder' => 'Nombre', 'class' => 'form-control')) }}
	    </div>
	    <div class="form-group">
	      {{ Form::label('description', 'Descripción') }}
	      {{ Form::textarea('description', null, array('placeholder' => 'Ingrese la descripción.', 'class' => 'form-control')) }}        
	    </div>
	    <div class="form-group">
            <label for="picture">Imagen</label>
            {{Form::file('picture',array('id'=>'picture'));}}
            <p class="help-block">Ésta es la imagen que acompañará la sección de la promoción.</p>
        </div>
	  {{ Form::button('Guardar', array('type' => 'submit', 'class' => 'btn btn-primary')) }}    
	  
	{{ Form::close() }}
</div><!-- row -->
@stop

app/views/promociones/index.blade.php
@extends('admin.layout')
@section('content')
<div class="row">
  <div class="col-lg-12">
    <h1>Promociones <small>Listado</small></h1>
    <ol class="breadcrumb">
      <li><a href="{{url('panel/promociones')}}"><i class="icon-dashboard"></i> Promociones</a></li>
      <li class="active"><i class="icon-file-alt"></i> Listado</li>
    </ol>
  </div>
</div><!-- /.row -->
<p>
	<a href="{{ route('panel.promociones.create') }}" class="btn btn-primary">Nueva promoción</a>
</p>
<div class="table-responsive">
	<table class="table table-hover">
		<thead>
			<th>#</th>
			<th>Nombre</th>
			<th>Editar</th>
			<th>Eliminar</th>
		</thead>
		<tbody>
			<?php $num = 0; ?>
			@foreach($promociones as $promocion)
			<?php $num++; ?>
			<tr>
				<td>{{$num}}</td>
				<td>{{$promocion->title}}</td>
				<td><a href="{{ route('panel.promociones.edit', $promocion->id) }}" class="btn btn-info">Editar</a></td>
				<td>
					{{ Form::model($promocion, array('route' => array('panel.promociones.destroy', $promocion->id), 'method' => 'DELETE', 'role' => 'form')) }}
        			{{ Form::submit('Eliminar', array('class' => 'btn btn-danger')) }}
        			{{ Form::close() }}
				</td>
			</tr>
			@endforeach
		</tbody>
	</table>
	{{ $promociones->links() }}
</div>
@stop

app/views/promociones/item_carrusel.blade.php
<div class="col-xs-4">
    <div class="portfolio-item">
        <div class="item-inner">
            <img class="img-responsive" src="{{url('uploads',$p->picture)}}" alt="">
            <h5>
                {{$p->title}}
            </h5>
            <div class="overlay">
                <a class="preview btn btn-danger" title="Ir a promociones" href="{{url('promociones')}}" rel="prettyPhoto"><i class="icon-eye-open"></i></a>
            </div>
        </div>
    </div>
</div>

app/views/promociones/mosaico.blade.php
<div class="row">
	<div class="col-md-5">
		
	</div>
	<div class="col-md-7">
		<h3>{{$p->title}}</h3>
	</div>
</div>
<div class="row">
	<div class="col-md-5">
		<a href="{{url('uploads',$p->picture)}}" data-toggle="lightbox" data-title="{{$p->title}}" title="Click para ampliar">
			<img class="thumbnail" style="max-width:260px; margin:auto;" src="{{url('uploads',$p->picture)}}">
		</a>
	</div>
	<div class="col-md-7">
		<p style="text-align:justify">{{$p->description}}</p>
	</div>
</div>