app/routes.php
<?php

// Nos mostrará el formulario de login.
Route::get('login', 'AuthController@showLogin');

// Validamos los datos de inicio de sesión.
Route::post('login', 'AuthController@postLogin');
Route::get('/panel/logout', 'AuthController@logOut');
Route::get('prueba', function(){
	return Hash::make('admin');
});
Route::get('/', function()
{
	return View::make('home', array(
		'activo'=>'inicio'
	));
});

Route::post('documentacion_pais', function()
{
	$pais = Input::get('pais');

	if (!View::exists('visas/'.$pais))
	{
	    App::abort(404);
	}

	return View::make('documentacion_pais', array(
		'pais'=>$pais,
		'nombre_pais'=>Visa::getNombrePais($pais)
	));
});

Route::get('empresa', function()
{
	$secciones_empresa = SeccionEmpresa::orderBy('id')->get();
	return View::make('empresa', array(
		'secciones_empresa'=>$secciones_empresa,
		'activo'=>'empresa'
	));
});
Route::get('/planes/nacionales', function()
{
	$planes = Plan::with('plan_tipo')->where('plan_tipo_id', 1)->paginate(6);
	return View::make('planes_nacionales', array(
		'planes'=> $planes,
		'activo'=>'planes'
	));
});
Route::get('/planes/internacionales', function()
{
	$planes = Plan::with('plan_tipo')->where('plan_tipo_id', 2)->paginate(6);
	return View::make('planes_internacionales', array(
		'planes'=> $planes,
		'activo'=>'planes'
	));
});
Route::get('/cruceros', function()
{
	$cruceros = Crucero::paginate(4);
	return View::make('cruceros', array(
		'cruceros'=> $cruceros,
		'activo'=>'cruceros'
	));
});
Route::get('/promociones', function()
{
	$promociones = Promocion::paginate(4);
	return View::make('promociones', array(
		'promociones'=> $promociones,
		'activo'=>'promociones'
	));
});
Route::resource('/seguro', 'SolicitudSeguroController');
Route::resource('/contacto', 'ContactoController');

Route::get('seguro_success', function(){
	return View::make('seguro_registrado', array(
		'activo'=>'seguro'
	));
});
Route::get('documentacion', function()
{
	return View::make('documentacion', array(
		'activo'=>'documentacion',
		'array_paises'=>Visa::paisesArray()
	));
});
Route::get('conoce_mas', function()
{
    return View::make('conoce_mas', array(
        'activo'=>'conoce_mas'
    ));
});

Route::get('no_auth', function()
{
	return View::make('admin/no_auth');
});

Route::group(array('before' => 'auth'), function()
{
	Route::get('/panel/cambiar_contrasena', 'AuthController@changePassword');
    Route::post('/panel/cambiar_contrasena', 'AuthController@updatePassword');

    Route::resource('/panel/creditos', 'CreditoController');
    Route::get('panel/search_by_doc', 'CreditoController@searchByDoc');
    Route::post('panel/search_by_doc_result', 'CreditoController@searchByDocResult');
    Route::get('panel/nuevo_pago/{id_credito}', function($id_credito)
    {
        $abono = new Abono();
        return View::make('creditos/nuevo_pago', array(
            'activo'=>'empresa',
            'id_credito'=>$id_credito,
            'abono'=>$abono
        ));
    });

    Route::resource('/panel/abonos', 'AbonoController');
});
Route::group(array('before' => 'auth|roles:1,no_auth'), function()
{
    Route::get('panel/nomina', 'CreditoController@searchNomina');
    Route::get('panel/closers_by_office', 'CreditoController@closersByOffice');
    Route::post('panel/search_nomina_result', 'CreditoController@searchNominaResult');

    Route::resource('panel/usuarios', 'UserController');
    Route::resource('/panel/planes', 'PlanController');
    Route::resource('/panel/oficinas', 'OficinaController');
    Route::resource('/panel/closers', 'CloserController');
    Route::resource('/panel/cruceros', 'CruceroController');
    Route::resource('/panel/promociones', 'PromocionController');
    Route::resource('/panel/documentacion', 'DocumentacionController');
    Route::resource('/panel', 'PaginaPrincipalController');

});

Route::group(array('before' => 'auth|roles:2-3,no_auth'), function()
{
	Route::get('ventas', function()
    {
        return View::make('admin/ventas', array(
            'activo'=>'empresa',
        ));
    });
});

app/views/admin/change_password.blade.php
@extends('admin.layout')
@section('content')
<div class="row">
  <div class="col-lg-12">
    <h1>Usuario <small>cambiar contraseña</small></h1>
    <ol class="breadcrumb">
      <li><a href="{{url('panel')}}"><i class="icon-dashboard"></i> panel</a></li>
      <li class="active"><i class="icon-file-alt"></i> cambiar contraseña</li>
    </ol>
  </div>
</div><!-- /.row -->
<div>
	@include ('errors', array('errors' => $errors)) 
</div>
<div>
	{{ Form::open(array('url' => '/panel/cambiar_contrasena')) }}
	    <div class="form-group">
	      	{{ Form::label('contrasena_anterior', 'Contraseña anterior') }}
	     	{{ Form::password('contrasena_anterior', array('placeholder' => 'Contraseña anterior', 'class' => 'form-control')) }}
	    </div>
	    <div class="form-group">
	      	{{ Form::label('nueva_contrasena', 'Nueva contraseña') }}
	     	{{ Form::password('nueva_contrasena', array('placeholder' => 'Nueva contraseña', 'class' => 'form-control')) }}
	    </div>
	    <div class="form-group">
	      	{{ Form::label('nueva_contrasena_confirmation', 'Confirmar contraseña') }}
	     	{{ Form::password('nueva_contrasena_confirmation', array('placeholder' => 'Confirmar contraseña', 'class' => 'form-control')) }}
	    </div>
	  {{ Form::button('Guardar', array('type' => 'submit', 'class' => 'btn btn-primary')) }}    
	  
	{{ Form::close() }}
</div><!-- row -->
@stop

app/views/admin/layout.blade.php
<?php
  $activo = isset($activo) ? $activo : 'index';
?>
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>VIP Tours Admin</title>

    <!-- Bootstrap core CSS -->
    <link href="{{asset('assets/css/bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{asset('assets/css/datepicker.css')}}" rel="stylesheet">

    <!-- Add custom CSS here -->
    <link href="{{asset('assets/css/sb-admin.css')}}" rel="stylesheet">
    <link href="{{asset('assets/font-awesome/css/font-awesome.min.css')}}" rel="stylesheet">
  </head>

  <body>

    <div id="wrapper">

      <!-- Sidebar -->
      <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{{url('panel')}}">VIP Tours Admin</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav side-nav">
            <li id="menu-empresa" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bar-chart-o"></i> Empresa<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <?php if(Auth::user()->role_id == 1): ?>
                <li><a href="{{ route('panel.usuarios.index') }}">Usuarios</a></li>
                <li><a href="{{ route('panel.oficinas.index') }}">Oficinas</a></li>
                <li><a href="{{ route('panel.closers.index') }}">Closers</a></li>
                <?php endif; ?>
                <li><a href="{{ route('panel.creditos.index') }}">Créditos</a></li>
                <li><a href="{{ url('panel/search_by_doc') }}">Búsqueda</a></li>
                <?php if(Auth::user()->role_id == 1): ?>
                <li><a href="{{ url('panel/nomina') }}">Nómina</a></li>
                <?php endif; ?>
              </ul>
            </li>
            <?php if(Auth::user()->role_id == 1): ?>
            <li id="menu-planes"><a href="{{ route('panel.planes.index') }}"><i class="fa fa-table"></i> Planes turísticos</a></li>
            <li id="menu-cruceros"><a href="{{ route('panel.cruceros.index') }}"><i class="fa fa-anchor"></i> Cruceros</a></li>
            <li id="menu-promociones"><a href="{{ route('panel.promociones.index') }}"><i class="fa fa-money"></i> Promociones</a></li>
            <?php endif; ?>
            <!--<li id="menu-seguro"><a href="bootstrap-elements.html"><i class="fa fa-plus"></i> Seguro de viaje</a></li>

            <li id="menu-contacto"><a href="blank-page.html"><i class="fa fa-envelope-o"></i> Contacto</a></li>-->
          </ul>

          <ul class="nav navbar-nav navbar-right navbar-user">
            <li class="dropdown user-dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> {{Auth::user()->name}} <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="{{url('/panel/cambiar_contrasena')}}"><i class="fa fa-user"></i> Cambiar contraseña</a></li>
                <li class="divider"></li>
                <li><a href="{{url('/panel/logout')}}"><i class="fa fa-power-off"></i> Cerrar sesión</a></li>
              </ul>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </nav>

      <div id="page-wrapper">
        @yield('content')
      </div><!-- /#page-wrapper -->

    </div><!-- /#wrapper -->

    <!-- JavaScript -->
    <script src="{{asset('assets/js/jquery-2.1.1.min.js')}}"></script>
    <script src="{{asset('assets/js/bootstrap.min.js')}}"></script>
    <script src="{{asset('assets/js/bootstrap-datepicker.js')}}"></script>
    <script src="{{asset('assets/js/global.js')}}"></script>
    <script type="text/javascript">
      (function(){
        $("#menu-{{$activo}}").addClass('active');
      })();
    </script>
  </body>
</html>

app/views/admin/layout_ventas.blade.php
<?php
  $activo = isset($activo) ? $activo : 'index';
?>
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>VIP Tours Admin</title>

    <!-- Bootstrap core CSS -->
    <link href="{{asset('assets/css/bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{asset('assets/css/datepicker.css')}}" rel="stylesheet">

    <!-- Add custom CSS here -->
    <link href="{{asset('assets/css/sb-admin.css')}}" rel="stylesheet">
    <link href="{{asset('assets/font-awesome/css/font-awesome.min.css')}}" rel="stylesheet">
  </head>

  <body>

    <div id="wrapper">

      <!-- Sidebar -->
      <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{{url('panel')}}">VIP Tours Admin</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav side-nav">
            <li id="menu-empresa" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bar-chart-o"></i> Empresa<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="{{ route('panel.closers.index') }}">Closers</a></li>
                <li><a href="{{ route('panel.creditos.index') }}">Créditos</a></li>
                <li><a href="{{ url('panel/search_by_doc') }}">Búsqueda</a></li>
                <li><a href="{{ url('panel/nomina') }}">Nómina</a></li>
              </ul>
            </li>
          </ul>

          <ul class="nav navbar-nav navbar-right navbar-user">
            <li class="dropdown user-dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> {{Auth::user()->name}} <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="{{url('/panel/cambiar_contrasena')}}"><i class="fa fa-user"></i> Cambiar contraseña</a></li>
                <li class="divider"></li>
                <li><a href="{{url('/panel/logout')}}"><i class="fa fa-power-off"></i> Cerrar sesión</a></li>
              </ul>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </nav>

      <div id="page-wrapper">
        @yield('content')
      </div><!-- /#page-wrapper -->

    </div><!-- /#wrapper -->

    <!-- JavaScript -->
    <script src="{{asset('assets/js/jquery-2.1.1.min.js')}}"></script>
    <script src="{{asset('assets/js/bootstrap.min.js')}}"></script>
    <script src="{{asset('assets/js/bootstrap-datepicker.js')}}"></script>
    <script src="{{asset('assets/js/global.js')}}"></script>
    <script type="text/javascript">
      (function(){
        $("#menu-{{$activo}}").addClass('active');
      })();
    </script>
  </body>
</html>

app/views/admin/login.blade.php
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>VIP Tours - Inicio de sesión</title>
        <link href="{{asset('assets/css/bootstrap.min.css')}}" rel="stylesheet">
    </head>
    <body>
        <div class="container" style="margin-top:30px">
            <div class="col-md-4 col-md-offset-4">
                <h1 class="text-center">VIP tours <br/> <small>Panel de administración</small></h1>
                <div class="login-panel panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Iniciar sesión</h3>
                    </div>
                    <div class="panel-body">
                        {{ Form::open(array('url' => '/login')) }}
                            <fieldset>
                                <div class="form-group">
                                    {{ Form::label('usuario', 'Nombre de usuario') }}
                                    {{ Form::text('username', null, array('class'=>'form-control', 'placeholder'=>'Usuario', 'autofocus'=>"")); }}
                                </div>
                                <div class="form-group">
                                    {{ Form::label('contraseña', 'Contraseña') }}
                                    {{ Form::password('password', array('class'=>'form-control', 'placeholder'=>'Contraseña', 'autofocus'=>"")); }}
                                </div>
                                <div class="checkbox">
                                    <label for="rememberme">
                                        {{ Form::checkbox('rememberme', true) }}Recordar contraseña
                                    </label>
                                </div>
                                <!-- Change this to a button or input when using this as a form -->
                                {{ Form::submit('Enviar', array('class'=>'btn btn-success')) }}
                                @if(Session::has('mensaje_error'))
                                    <br/><span>&nbsp;</span>
                                    <div class="alert alert-danger">
                                        {{ Session::get('mensaje_error') }}
                                    </div>
                                @endif
                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

app/views/admin/no_auth.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Acceso no autorizado</title>
    <link href="{{asset('assets/css/bootstrap.min.css')}}" rel="stylesheet">
</head>
<body>
	<div class="panel panel-primary" style="margin:3em;">
		<div class="panel-heading">
			<h3 class="panel-title">Acceso no autorizado</h3>
		</div>
		<div class="panel-body">Puede que su sesión haya caducado, o no tenga autorización para ver esta página.
		<a href="{{url('panel/logout')}}" class="btn btn-primary" style="float:right;">Ir al inicio</a>
		</div>
	</div>
</body>
</html>

app/views/admin/principal.blade.php
@extends('admin.layout')
<?php
    if ($datos->exists):
        $form_data = array('route' => array('panel.update', $datos->id), 'method' => 'PATCH', 'files' => true);
    else:
        $form_data = array('route' => 'panel.store', 'method' => 'POST', 'files' => true);
    endif;

?>
@section('content')
<div class="row">
  <div class="col-lg-12">
    <h1>Página principal <small>datos</small></h1>
    <ol class="breadcrumb">
      <li><a href="{{url('panel')}}"><i class="icon-dashboard"></i> Página principal</a></li>
      <li class="active"><i class="icon-file-alt"></i> datos</li>
    </ol>
  </div>
</div><!-- /.row -->
<div>
	@include ('errors', array('errors' => $errors)) 
</div>
<div>
	{{ Form::model($datos,$form_data, array('role' => 'form')) }}
	    <div class="form-group">
	      	{{ Form::label('titulo_uno', 'Título 1') }}
	     	{{ Form::text('titulo_uno', null, array('placeholder' => 'Título 1', 'class' => 'form-control')) }}
	    </div>
	    <div class="form-group">
	      	{{ Form::label('descripcion_uno', 'Descripción 1') }}
	     	{{ Form::text('descripcion_uno', null, array('placeholder' => 'Descripción 1', 'class' => 'form-control')) }}
	    </div>
	    <div class="form-group">
	      	{{ Form::label('titulo_dos', 'Título 2') }}
	     	{{ Form::text('titulo_dos', null, array('placeholder' => 'Título 2', 'class' => 'form-control')) }}
	    </div>
	    <div class="form-group">
	      	{{ Form::label('detalle_dos', 'Descripción 2') }}
	     	{{ Form::text('detalle_dos', null, array('placeholder' => 'Descripción 2', 'class' => 'form-control')) }}
	    </div>
	    <div class="form-group">
	      	{{ Form::label('titulo_tres', 'Título 3') }}
	     	{{ Form::text('titulo_tres', null, array('placeholder' => 'Título 3', 'class' => 'form-control')) }}
	    </div>
	    <div class="form-group">
	      	{{ Form::label('detalle_tres', 'Descripción tres') }}
	     	{{ Form::text('detalle_tres', null, array('placeholder' => 'Descripción 3', 'class' => 'form-control')) }}
	    </div>
	    <div class="form-group">
	      	{{ Form::label('url_video', 'URL vídeo') }}
	     	{{ Form::text('url_video', null, array('placeholder' => 'URL del vídeo de YouTube', 'class' => 'form-control')) }}
	    </div>
	    <div class="form-group">
	      	{{ Form::label('ver_mas', 'Ver más') }}
	     	{{ Form::textarea('ver_mas', null, array('placeholder' => 'Texto de la sección "Ver más"', 'class' => 'form-control')) }}
	    </div>
	    <div class="form-group">
	      	{{ Form::label('email_notificaciones', 'e-mail para notificaciones') }}
	     	{{ Form::text('email_notificaciones', null, array('placeholder' => 'e-maio donde recibirá las solicitudes de seguro y mensajes de contacto"', 'class' => 'form-control')) }}
	    </div>
	  {{ Form::button('Guardar', array('type' => 'submit', 'class' => 'btn btn-primary')) }}    
	  
	{{ Form::close() }}
</div><!-- row -->
@stop

app/views/admin/ventas.blade.php
@extends('admin.layout')
<?php
    /*if ($datos->exists):
        $form_data = array('route' => array('panel.update', $datos->id), 'method' => 'PATCH', 'files' => true);
    else:
        $form_data = array('route' => 'panel.store', 'method' => 'POST', 'files' => true);
    endif;*/

?>
@section('content')
<div class="row">
  <div class="col-lg-12">
    <h1>Página principal <small>datos</small></h1>
    <ol class="breadcrumb">
      <li><a href="{{url('panel')}}"><i class="icon-dashboard"></i> Página principal</a></li>
      <li class="active"><i class="icon-file-alt"></i> datos</li>
    </ol>
  </div>
</div><!-- /.row -->
<div>
	@include ('errors', array('errors' => $errors)) 
</div>
<div>
	
</div><!-- row -->
@stop