app/routes.php
<?php

// Nos mostrará el formulario de login.
Route::get('login', 'AuthController@showLogin');

// Validamos los datos de inicio de sesión.
Route::post('login', 'AuthController@postLogin');
Route::get('/panel/logout', 'AuthController@logOut');
Route::get('prueba', function(){
	return Hash::make('admin');
});
Route::get('/', function()
{
	return View::make('home', array(
		'activo'=>'inicio'
	));
});

Route::post('documentacion_pais', function()
{
	$pais = Input::get('pais');

	if (!View::exists('visas/'.$pais))
	{
	    App::abort(404);
	}

	return View::make('documentacion_pais', array(
		'pais'=>$pais,
		'nombre_pais'=>Visa::getNombrePais($pais)
	));
});

Route::get('empresa', function()
{
	$secciones_empresa = SeccionEmpresa::orderBy('id')->get();
	return View::make('empresa', array(
		'secciones_empresa'=>$secciones_empresa,
		'activo'=>'empresa'
	));
});
Route::get('/planes/nacionales', function()
{
	$planes = Plan::with('plan_tipo')->where('plan_tipo_id', 1)->paginate(6);
	return View::make('planes_nacionales', array(
		'planes'=> $planes,
		'activo'=>'planes'
	));
});
Route::get('/planes/internacionales', function()
{
	$planes = Plan::with('plan_tipo')->where('plan_tipo_id', 2)->paginate(6);
	return View::make('planes_internacionales', array(
		'planes'=> $planes,
		'activo'=>'planes'
	));
});
Route::get('/cruceros', function()
{
	$cruceros = Crucero::paginate(4);
	return View::make('cruceros', array(
		'cruceros'=> $cruceros,
		'activo'=>'cruceros'
	));
});
Route::get('/promociones', function()
{
	$promociones = Promocion::paginate(4);
	return View::make('promociones', array(
		'promociones'=> $promociones,
		'activo'=>'promociones'
	));
});
Route::resource('/seguro', 'SolicitudSeguroController');
Route::resource('/contacto', 'ContactoController');

Route::get('seguro_success', function(){
	return View::make('seguro_registrado', array(
		'activo'=>'seguro'
	));
});
Route::get('documentacion', function()
{
	return View::make('documentacion', array(
		'activo'=>'documentacion',
		'array_paises'=>Visa::paisesArray()
	));
});
Route::get('conoce_mas', function()
{
    return View::make('conoce_mas', array(
        'activo'=>'conoce_mas'
    ));
});

Route::get('no_auth', function()
{
	return View::make('admin/no_auth');
});

Route::group(array('before' => 'auth'), function()
{
	Route::get('/panel/cambiar_contrasena', 'AuthController@changePassword');
    Route::post('/panel/cambiar_contrasena', 'AuthController@updatePassword');

    Route::resource('/panel/creditos', 'CreditoController');
    Route::get('panel/search_by_doc', 'CreditoController@searchByDoc');
    Route::post('panel/search_by_doc_result', 'CreditoController@searchByDocResult');
    Route::get('panel/nuevo_pago/{id_credito}', function($id_credito)
    {
        $abono = new Abono();
        return View::make('creditos/nuevo_pago', array(
            'activo'=>'empresa',
            'id_credito'=>$id_credito,
            'abono'=>$abono
        ));
    });

    Route::resource('/panel/abonos', 'AbonoController');
});
Route::group(array('before' => 'auth|roles:1,no_auth'), function()
{
    Route::get('panel/nomina', 'CreditoController@searchNomina');
    Route::get('panel/closers_by_office', 'CreditoController@closersByOffice');
    Route::post('panel/search_nomina_result', 'CreditoController@searchNominaResult');

    Route::resource('panel/usuarios', 'UserController');
    Route::resource('/panel/planes', 'PlanController');
    Route::resource('/panel/oficinas', 'OficinaController');
    Route::resource('/panel/closers', 'CloserController');
    Route::resource('/panel/cruceros', 'CruceroController');
    Route::resource('/panel/promociones', 'PromocionController');
    Route::resource('/panel/documentacion', 'DocumentacionController');
    Route::resource('/panel', 'PaginaPrincipalController');

});

Route::group(array('before' => 'auth|roles:2-3,no_auth'), function()
{
	Route::get('ventas', function()
    {
        return View::make('admin/ventas', array(
            'activo'=>'empresa',
        ));
    });
});

app/models/Credito.php
<?php

class Credito extends Eloquent{
	public $errors;
	protected $table = 'creditos';
	protected $fillable = array('numero','fecha','gl','valor_contrato','saldo','nombres_titular','apellidos_titular',
        'cedula_titular','cootitulares','direccion_titular','telefono_titular','celular_titular','email_titular',
        'vigencia', 'duracion', 'producto_solicitado', 'liner', 'closer_id', 'beneficiarios', 'estado', 'user_id',
        'servicio_cliente', 'observaciones', 'devolucion');

	public function isValid($data)
    {
        $rules = array(
        	'numero'		    => 'required|max:255',
            'gl' 	            => 'required|integer',
            'valor_contrato' 	=> 'required|integer',
            'nombres_titular'   => 'required|max:255',
            'apellidos_titular'	=> 'required|max:255',
            'beneficiarios'     => 'max:255',
            'cedula_titular'	=> 'required|max:255',
            'closer_id'	        => 'required|integer',
            'primer_abono'      => 'numeric'
        );
        
        $validator = Validator::make($data, $rules);
        
        if ($validator->passes())
        {
            return true;
        }
        
        $this->errors = $validator->errors();
        
        return false;
    }

    public function closer()
    {
        return $this->belongsTo('Closer','closer_id');
    }

    public function user()
    {
        return $this->belongsTo('User','user_id');
    }
}

app/controllers/CreditoController.php
<?php

class CreditoController extends \BaseController {

    /**
     * Muestra un formulario para hacer una búsqueda de
     * créditos por la cédula del propietario
     * @return mixed
     */
    public function searchByDoc()
    {
        return View::make('creditos/search_by_doc', array(
            'activo'=>'empresa'
        ));
    }

    public function searchNomina()
    {
    	$oficinas_a = Oficina::oficinasArray();
    	$oficinas = array(0=>'TODAS');
    	foreach($oficinas_a as $i => $oa){
    		$oficinas[$i] = $oa;
    	}
        return View::make('creditos/search_nomina', array(
            'activo'=>'empresa',
            'oficinas_a'=>$oficinas,
        ));
    }

    public function closersByOffice()
    {
    	$oficina = Input::get('oficina');
    	$closers = Closer::where('oficina_id',$oficina)->orderBy('nombre')->get();
    	$options = "<option value='0'>TODOS</option>";
    	foreach($closers as $c){
    		$options .= "<option value='$c->id'>$c->nombre</option>";
    	}
    	return $options;
    }

    /**
     * Muestra la lista de resultados obtenidos de buscar
     * créditos pertenecientes a la cédula introducida en
     * el formulario que muestra el método 'searchByDoc'
     * @return mixed
     */
    public function searchByDocResult()
    {
        $cedula = Input::get('cedula_titular');
        $creditos = Credito::with('closer')->where('cedula_titular',"$cedula")->orderBy('fecha', 'desc')->paginate(10);

        return View::make('creditos/search_by_doc_result', array(
            'activo'=>'empresa',
            'creditos'=>$creditos
        ));
    }

    public function searchNominaResult()
    {
    	
    	$desde = Input::get('desde');
    	$hasta = Input::get('hasta');
    	$oficina = Input::get('oficina_id');
    	$closer = Input::get('closer_id');

    	$abonos = Abono::with('credito')
    		->whereIn('credito_id', function($query){
    			$query->select('id')->from('creditos')
                    ->where('devolucion', 0)
                    ->whereBetween('fecha',array(Input::get('desde'), Input::get('hasta')))
    				->orderBy('closer_id');
    		})
			->groupBy('credito_id')->orderBy('created_at')->get();

    	if($oficina != 0 && $closer != 0){

    		$abonos = Abono::with('credito')
    		->whereIn('credito_id', function($query){
    			$query->select('id')->from('creditos')
                    ->where('devolucion', 0)
                    ->whereBetween('fecha',array(Input::get('desde'), Input::get('hasta')))
    				->where('closer_id', Input::get('closer_id'))->orderBy('closer_id');
    		})
			->groupBy('credito_id')->orderBy('created_at')->get();

    	}else if($oficina != 0){

    		$abonos = Abono::with('credito')
    		->whereIn('credito_id', function($query){
    			$query->select('id')->from('creditos')
                    ->where('devolucion', 0)
                    ->whereBetween('fecha',array(Input::get('desde'), Input::get('hasta')))
    				->whereIn('closer_id', function($query){
    					$query->select('id')->from('closers')->where('oficina_id',Input::get('oficina_id'));
    				})->orderBy('closer_id');
    		})
			->groupBy('credito_id')->orderBy('created_at')->get();
    	}
		
		$total_total = 0;
		$total_comision = 0;

		foreach($abonos as $a){
			$porcentaje = round($a->valor * 100 / $a->credito->valor_contrato);
			$a->porcentaje = $porcentaje;
			$porcentaje_comision = 0;
			
			if($porcentaje == 100){
				if($a->credito->valor_contrato >= 6000000){
					$porcentaje_comision = $a->credito->closer->porcentaje_100_mayor_seis;
				}else if($a->credito->valor_contrato >= 4000000){
					$porcentaje_comision = $a->credito->closer->porcentaje_100_mayor_cuatro;
				}else if($a->credito->valor_contrato >= 1440000){
					$porcentaje_comision = $a->credito->closer->porcentaje_100_mayor_uno_cuatro_cuarenta;
				}
			}else if($a->porcentaje >= 50){
				$porcentaje_comision = $a->credito->closer->porcentaje_50;
			}
			$a->porcentaje_comision = $porcentaje_comision;
			$a->total_a_pagar = round($a->credito->valor_contrato * $porcentaje_comision / 100);
			
			$total_total += $a->credito->valor_contrato;
			$total_comision += $a->total_a_pagar;
		}

        return View::make('creditos/search_nomina_result', array(
            'activo'=>'empresa',
            'abonos'=>$abonos,
            'total_total'=>$total_total,
            'total_comision'=>$total_comision
        ));
    }

    public function nuevoPago()
    {
        print_r(Input::get('id_credito'));
    }

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		if(in_array(Auth::user()->role_id, array(1, 3))){
			$creditos = Credito::with('closer')->orderBy('fecha', 'desc')->paginate(10);
		}else{
			$creditos = Credito::with('closer')->where('user_id', Auth::user()->id)->orderBy('fecha', 'desc')->paginate(10);
		}
		
		return View::make('creditos.index', array(
			'creditos'=>$creditos,
			'activo'=>'empresa'
			)
		);
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
        if(Auth::user()->role_id == 3){
            return Redirect::to('/no_auth');
        }
        $credito = new Credito();
		$closers_a = Closer::closersArray();
		return View::make('creditos.form', array(
			'credito'=> $credito,
			'closers_a'=>$closers_a,
			'action'=>'Nuevo',
			'activo'=>'empresa'
			)
		);
	}


	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
        if(Auth::user()->role_id == 3){
            return Redirect::to('/no_auth');
        }
        $credito = new Credito;
        $data = Input::all();

        // Revisamos si la data es válida
        if ($credito->isValid($data))
        {
            // Si la data es valida se la asignamos al usuario
            $credito->fill($data);
            if($credito->saldo == null || $credito->saldo == 0 || $credito->saldo == ''){
            	$credito->saldo = $credito->valor_contrato;
            	$credito->user_id = Auth::user()->id;
            }
            $credito->servicio_cliente .= '|';
            $credito->observaciones .= '|';

            $credito->save();

            $valor_primer_abono = (is_numeric(Input::get('primer_abono'))) ? Input::get('primer_abono') : 0;

            if($valor_primer_abono > 0){
                $primer_abono = new Abono();
                $primer_abono->credito_id = $credito->id;
                $primer_abono->valor = $valor_primer_abono;
                $primer_abono->nuevo_saldo = 0;
                $primer_abono->save();

                $suma_abonos = Abono::where('credito_id', $primer_abono->credito_id)->sum('valor');
                $nuevo_saldo = $credito->valor_contrato - $suma_abonos;

                $credito->saldo = $nuevo_saldo;
                $credito->save();

                $primer_abono->nuevo_saldo = $nuevo_saldo;
                $primer_abono->save();
            }
            
            Return Redirect::to('panel/creditos');
        }
        else
        {
            // En caso de error regresa a la acción create con los datos y los errores encontrados
			return Redirect::route('panel.creditos.create')->withInput()->withErrors($credito->errors);
        }
	}


	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$credito = Credito::find($id);
		$abonos = Abono::where('credito_id', $id)->orderBy('id')->get();
		if (is_null ($credito))
		{
			App::abort(404);
		}
		$closers_a = Closer::closersArray();
        $servicio_cliente = explode('|', $credito->servicio_cliente);
        array_pop($servicio_cliente);
        $observaciones = explode('|', $credito->observaciones);
        array_pop($observaciones);
		return View::make('creditos.detalle', array(
			'credito'=> $credito,
			'abonos'=>$abonos,
			'closers_a'=>$closers_a,
			'action'=>'Detalle',
			'activo'=>'empresa',
            'servicio_cliente'=>$servicio_cliente,
            'observaciones'=>$observaciones
			)
		);
	}


	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
        if(Auth::user()->role_id != 1){
            return Redirect::to('/panel/no_auth');
        }
        $credito = Credito::find($id);
		if (is_null ($credito))
		{
			App::abort(404);
		}
        $credito->servicio_cliente = '';
        $credito->observaciones = '';
		$closers_a = Closer::closersArray();
		return View::make('creditos.form', array(
			'credito'=> $credito,
			'closers_a'=>$closers_a,
			'action'=>'Editar',
			'activo'=>'empresa'
			)
		);
		//return View::make('admin/users/form')->with('user', $user);
	}


	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
        if(Auth::user()->role_id != 1){
            return Redirect::to('/no_auth');
        }
        $credito = Credito::find($id);
        if (is_null ($credito))
        {
            App::abort(404);
        }
        $servicio_cliente = $credito->servicio_cliente;
        $observaciones = $credito->observaciones;
        
        // Obtenemos la data enviada por el usuario
        $data = Input::all();
        
        // Revisamos si la data es válido
        if ($credito->isValid($data))
        {
            $credito->fill($data);
            $credito->servicio_cliente = $servicio_cliente.Input::get('servicio_cliente').'|';
            $credito->observaciones = $observaciones.Input::get('observaciones').'|';
            $credito->save();
            // Y Devolvemos una redirección a la acción show para mostrar el usuario
            return Redirect::route('panel.creditos.index');
        }
        else
        {
            // En caso de error regresa a la acción edit con los datos y los errores encontrados

app/views/creditos/detalle.blade.php
@extends('admin.layout')
<?php
    if ($credito->exists):
        $form_data = array('route' => array('panel.creditos.update', $credito->id), 'method' => 'PATCH', 'files' => true);
    else:
        $form_data = array('route' => 'panel.creditos.store', 'method' => 'POST', 'files' => true);
    endif;

?>
@section('content')
<div class="row">
  <div class="col-lg-12">
    <h1>Crédito <small>{{ $action }}</small></h1>
    <ol class="breadcrumb">
      <li><a href="{{url('panel/creditos')}}"><i class="icon-dashboard"></i> Créditos</a></li>
      <li><a href="{{url('panel/search_by_doc')}}"><i class="icon-dashboard"></i> Búsqueda</a></li>
      <li class="active"><i class="icon-file-alt"></i> {{ $action }}</li>
    </ol>
  </div>
</div><!-- /.row -->
<div>
	@include ('errors', array('errors' => $errors)) 
</div>
<div>

	    <div class="form-group">
	      	{{ Form::label('fecha', 'General') }}
	    </div>
	    <table class="table table-bordered">
			<tr>
				<th>Fecha</th>
				<th>Número de contrato</th>
				<th>Liner</th>
				<th>Closer</th>
			</tr>
			<tr>
				<td>{{ $credito->fecha }}</td>
				<td>{{ $credito->numero }}</td>
				<td>{{ $credito->liner }}</td>
				<td>{{ $credito->closer->nombre }}</td>
			</tr>
		</table>
	    <table class="table table-bordered">
			<tr>
				<th>G.A.</th>
				<th>VALOR</th>
				<th>SALDO</th>
				<th>VIGENCIA</th>
			</tr>
			<tr>
				<td>$ {{ number_format($credito->gl, 0, ',', '.') }}</td>
				<td>$ {{ number_format($credito->valor_contrato, 0, ',', '.') }}</td>
				<td>$ {{ number_format($credito->saldo, 0, ',', '.') }}</td>
				<td>{{ $credito->vigencia }}</td>
			</tr>
		</table>
		{{ Form::label('titular', 'TITULAR') }}
		<table class="table table-bordered">
			<tr>
				<th>NOMBRES</th>
				<th>APELLIDOS</th>
				<th>C.C.</th>
				<th>CELULAR</th>
				<th>E-MAIL</th>
			</tr>
			<tr>
				<td>{{ $credito->nombres_titular }}</td>
				<td>{{ $credito->apellidos_titular }}</td>
				<td>{{ $credito->cedula_titular }}</td>
				<td>{{ $credito->celular_titular }}</td>
				<td>{{ $credito->email_titular }}</td>
			</tr>
		</table>
		{{ Form::label('cotitular', 'COTITULAR') }}
		<table class="table table-bordered">
			<tr>
				<th colspan="2">NOMBRES Y APELLIDOS</th>
			</tr>
			<tr>
				<td colspan="2">{{ $credito->cootitulares }}</td>
			</tr>
		</table>
		<table class="table table-bordered">
			<tr>
				<th colspan="2">BENEFICIARIOS</th>
			</tr>
			<tr>
				<td colspan="2">{{ $credito->beneficiarios }}</td>
			</tr>
		</table>
		<table class="table table-bordered">
			<tr>
				<th colspan="2">PRODUCTO SOLICITADO</th>
			</tr>
			<tr>
				<td colspan="2">{{ $credito->producto_solicitado }}</td>
			</tr>
		</table>
		<table class="table table-bordered">
            <tr>
                <th colspan="2">SERVICIO AL CLIENTE</th>
            </tr>
            <tr>
                <td colspan="2">
                    <ul>
                        @foreach($servicio_cliente as $sc)
                        <li>{{$sc}}</li>
                        @endforeach
                    </ul>
                </td>
            </tr>
        </table>
        <table class="table table-bordered">
            <tr>
                <th colspan="2">OBSERVACIONES</th>
            </tr>
            <tr>
                <td colspan="2">
                    <ul>
                        @foreach($observaciones as $ob)
                        <li>{{$ob}}</li>
                        @endforeach
                    </ul>
                </td>
            </tr>
        </table>
	    {{ Form::label('cartera', 'CARTERA') }}
		<table class="table table-bordered">
			<tr>
				<th>#</th>
				<th>FECHA</th>
				<th>ABONO</th>
			</tr>
			@foreach($abonos as $i => $abono)
			<tr>
				<td>{{ ($i + 1) }}</td>
				<td>{{ substr($abono->created_at, 0, 10) }}</td>
				<td>$ {{ number_format($abono->valor, 0, ',', '.') }}</td>
			</tr>
			@endforeach
		</table>

        <table class="table table-bordered">
            <tr>
                <th colspan="2">SALDO</th>
            </tr>
            <tr>
                <td colspan="2">
                    $ <?= number_format($credito->saldo, 0, ',', '.') ?>
                </td>
            </tr>
        </table>
</div><!-- row -->
@stop

app/views/creditos/index.blade.php
@extends('admin.layout')
@section('content')
<div class="row">
  <div class="col-lg-12">
    <h1>Créditos <small>Listado</small></h1>
    <ol class="breadcrumb">
      <li><a href="{{url('panel/creditos')}}"><i class="icon-dashboard"></i> Créditos</a></li>
      <li class="active"><i class="icon-file-alt"></i> Listado</li>
    </ol>
  </div>
</div><!-- /.row -->
<p>
	<a href="{{ route('panel.creditos.create') }}" class="btn btn-primary">Crear un nuevo crédito</a>
</p>
<div class="table-responsive">
	<table class="table table-hover">
		<thead>
			<th>#</th>
			<th>Número</th>
			<th>fecha</th>
			<th>Titular</th>
			<th>Cédula</th>
			<th>Valor</th>
			<th>Saldo</th>
			<th>Ver</th>
			<?php if(Auth::user()->role_id == 1): ?>
			<th>Editar</th>
			<th>Eliminar</th>
			<?php endif; ?>
		</thead>
		<tbody>
			<?php $num = 0; ?>
			@foreach($creditos as $credito)
			<?php $num++; ?>
			<tr class="<?= ($credito->devolucion == 1) ? 'bg-danger' : '' ?>">
				<td>{{$num}}</td>
				<td>{{$credito->numero}}</td>
				<td>{{$credito->fecha}}</td>
				<td>{{$credito->nombres_titular . ' ' . $credito->apellidos_titular}}</td>
				<td>{{$credito->cedula_titular}}</td>
				<td>{{ "$ ".number_format($credito->valor_contrato, 0, ',','.') }}</td>
				<td>{{ "$ ".number_format($credito->saldo, 0, ',','.') }}</td>
				<td><a href="{{ url('panel/creditos', $credito->id) }}" class="btn btn-success">Ver</a></td>
				<?php if(Auth::user()->role_id == 1): ?>
				<td><a href="{{ route('panel.creditos.edit', $credito->id) }}" class="btn btn-info">Editar</a></td>
				<td>
					{{ Form::model($credito, array('route' => array('panel.creditos.destroy', $credito->id), 'method' => 'DELETE', 'role' => 'form')) }}
        			{{ Form::submit('Eliminar', array('class' => 'btn btn-danger')) }}
        			{{ Form::close() }}
				</td>
				<?php endif; ?>
			</tr>
			@endforeach
		</tbody>
	</table>
	{{ $creditos->links() }}
</div>
@stop

app/views/creditos/search_by_doc.blade.php
@extends('admin.layout')
@section('content')
<div class="row">
  <div class="col-lg-12">
    <h1>Crédito <small>búsqueda</small></h1>
    <ol class="breadcrumb">
      <li><a href="{{url('panel/creditos')}}"><i class="icon-dashboard"></i> Créditos</a></li>
      <li class="active"><i class="icon-file-alt"></i> búsqueda</li>
    </ol>
  </div>
</div><!-- /.row -->
<div>
	@include ('errors', array('errors' => $errors)) 
</div>
<div>
	{{ Form::open(array('role' => 'form', 'url'=>'panel/search_by_doc_result'))}}
	    <div class="form-group">
	      	{{ Form::label('cedula_titular', 'Cedula titular') }}
	     	{{ Form::text('cedula_titular', null, array('placeholder' => 'Cédula del titular', 'class' => 'form-control')) }}
	    </div>
	  {{ Form::button('Consultar', array('type' => 'submit', 'class' => 'btn btn-primary')) }}
	  
	{{ Form::close() }}
</div><!-- row -->
@stop

app/views/creditos/search_by_doc_result.blade.php
@extends('admin.layout')
@section('content')
<div class="row">
  <div class="col-lg-12">
    <h1>Créditos <small>Búsqueda</small></h1>
    <ol class="breadcrumb">
      <li><a href="{{url('panel/creditos')}}"><i class="icon-dashboard"></i> Créditos</a></li>
      <li><a href="{{url('panel/search_by_doc')}}"><i class="icon-dashboard"></i> Búsqueda</a></li>
      <li class="active"><i class="icon-file-alt"></i> Resultado</li>
    </ol>
  </div>
</div><!-- /.row -->

<div class="table-responsive">
	<table class="table table-hover">
		<thead>
			<th>#</th>
			<th>Número</th>
			<th>fecha</th>
			<th>Titular</th>
			<th>Cédula</th>
			<th>Valor</th>
			<th>Saldo</th>
			<th>Detalle</th>
			<?php if(Auth::user()->role_id == 1): ?>
			<th>Editar</th>
			<th>Eliminar</th>
			<?php endif; ?>
			<?php if( in_array (Auth::user()->role_id, array(1, 2))): ?>
			<th>Agregar pago</th>
			<?php endif; ?>
			<th>Historial pagos</th>
		</thead>
		<tbody>
			<?php $num = 0; ?>
			@foreach($creditos as $credito)
			<?php $num++; ?>
			<tr class="<?= ($credito->devolucion == 1) ? 'bg-danger' : '' ?>">
				<td>{{$num}}</td>
				<td>{{$credito->numero}}</td>
				<td>{{$credito->fecha}}</td>
				<td>{{$credito->nombres_titular . ' ' . $credito->apellidos_titular}}</td>
				<td>{{$credito->cedula_titular}}</td>
				<td>{{ "$ ".number_format($credito->valor_contrato, 0, ',','.') }}</td>
				<td>{{ "$ ".number_format($credito->saldo, 0, ',','.') }}</td>
				<td><a href="{{ url('panel/creditos', $credito->id) }}" class="btn btn-warning">Ver</a></td>
				<?php if(Auth::user()->role_id == 1): ?>
				<td><a href="{{ route('panel.creditos.edit', $credito->id) }}" class="btn btn-info">Editar</a></td>
				<td>
                    {{ Form::model($credito, array('route' => array('panel.creditos.destroy', $credito->id), 'method' => 'DELETE', 'role' => 'form')) }}
                    {{ Form::submit('Eliminar', array('class' => 'btn btn-danger')) }}
                    {{ Form::close() }}
                </td>
                <?php endif; ?>
			    <?php if( in_array (Auth::user()->role_id, array(1, 2))): ?>
				<td><a href="{{ url('panel/nuevo_pago', $credito->id) }}" class="btn btn-success">Agregar</a></td>
			    <?php endif; ?>
				<td><a href="{{ url('panel/abonos/'. $credito->id) }}" class="btn btn-info">Ver pagos</a></td>
			</tr>
			@endforeach
		</tbody>
	</table>
	{{ $creditos->links() }}
</div>
@stop